version: '3.7'

services:
  front_end:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      URL_SERVICIOS: https://servicios:443
      CLIENTE_SERVICIOS_USR: ${CLIENTE_SERVICIOS_USR}
      CLIENTE_SERVICIOS_PWD: ${CLIENTE_SERVICIOS_PWD}
    build: .
    restart: always
    container_name: front_end
    volumes:
      - ./front_end:/code
      - ./config/nginx/certs/manjaro_cert.crt:/tmp/servicios_cert.crt:ro
    depends_on:
      - bd
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500M"
  bd:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/certs:/tmp/
      - ./front_end/static:/static
    depends_on:
      - front_end
    ports:
      - 443:443
