# Generated by Django 3.0.5 on 2020-06-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombreAdmin', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('ip_servidor', models.CharField(max_length=16)),
                ('tokenTelegram', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
