# Generated by Django 3.0.5 on 2020-06-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
