# Generated by Django 3.0.5 on 2020-06-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='servidores',
        ),
    ]
