# Generated by Django 3.0.5 on 2020-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_delete_servidores'),
    ]

    operations = [
        migrations.CreateModel(
            name='relacion_user_servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=30)),
                ('ip_servidor', models.CharField(max_length=16)),
                ('mac', models.CharField(max_length=18)),
                ('hostname', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='user_telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=30)),
                ('tokenTelegram', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=20)),
            ],
        ),
    ]
