# Generated by Django 3.0.5 on 2020-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_relacion_user_servidor_user_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_logueado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='administradores',
        ),
    ]
