# Generated by Django 3.0.7 on 2020-07-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20200619_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacion_user_servidor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='relacion_user_servidor',
            name='token',
        ),
        migrations.AddField(
            model_name='relacion_user_servidor',
            name='password_api',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='relacion_user_servidor',
            name='usuario_api',
            field=models.CharField(default=0, max_length=18),
        ),
    ]
