# Generated by Django 3.0.7 on 2020-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoria_ram', models.CharField(max_length=5)),
                ('memoria_swap', models.CharField(max_length=5)),
                ('espacio_disco', models.CharField(max_length=5)),
            ],
        ),
    ]
