# Generated by Django 3.0.7 on 2020-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servidor_numero_procesadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='espacio_disco',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='memoria_ram',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='memoria_swap',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
